name: myportfolio
description: "Web Portfolio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  get: ^4.7.2
  intl: ^0.20.2
  webviewx_plus: ^0.5.1+1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  #google_fonts:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/games/
    - assets/images/apps/
