name: githubweb
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  url_launcher: ^5.5.0
  google_fonts: ^1.1.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/

