name: myportfolio
description: "Web Portfolio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  intl: 0.19.0
  webviewx: ^0.2.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  #auto_size_text: ^3.0.0
  #google_fonts:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/games/
    - assets/images/apps/
